### ISSUE TITLE
Make examples build optional

### ISSUE THREAD

**Issue by patrick-stephens** [fluent/ctraces#20]
The building of the examples requires extra dependencies and so should be optional for any consumers of this library.

Assumption should be to disable by default to simplify usage by consumers.
If disabled by default then ensure it is enabled in the CI to exercise the full build.

**Comment by Syn3rman** [comment]
@patrick-stephens closing this since CTR_EXAMPLES should handle this

**Comment by edsiper** [comment]
@patrick-stephens it's already there:

https://github.com/calyptia/ctraces/blob/master/CMakeLists.txt#L43
